{% set name = "faim-ipa" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/faim_ipa-{{ version }}.tar.gz
  sha256: 57ab6f0dba5d304caf5fb82aa511a6fdfff008c9e2d9efa73b4d777e18d132cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.10
    - defusedxml
    - distributed
    - matplotlib-base
    - numpy <2
    - ome-zarr
    - pandas
    - pint
    - pydantic >=2
    - questionary
    - scikit-image
    - tqdm

test:
  imports:
    - faim_ipa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fmi-faim/faim-ipa
  summary: Tools used at FMI-FAIM for Image Processing and Analysis.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - imagejan
    - tibuch
